### ISSUE TITLE
Really low accuracy on NTU RGB D 120

### ISSUE THREAD

**Issue by Anirudh257** [limaosen0/AS-GCN#13]
Firstly, thanks a lot for making the code public. I am trying to train AS-GCN on the cross-setup setting as described in [NTU RGB D 120](https://arxiv.org/pdf/1905.04757.pdf). For performing this experiment, I am doing the following steps:
1) Making changes in the preprocessing file to create new data with 120 classes and even setups for training and odd setups for testing.

2) I make the changes in the yaml config file and following the same procedure as given for the NTU RGB 60. 

I am getting decent accuracy for the **Cross-Subject protocol** but really low on **Cross setup**. 
What can be the reason for this?

**Comment by Roy790422795** [comment]
> Firstly, thanks a lot for making the code public. I am trying to train AS-GCN on the cross-setup setting as described in [NTU RGB D 120](https://arxiv.org/pdf/1905.04757.pdf). For performing this experiment, I am doing the following steps:
> 
> 1. Making changes in the preprocessing file to create new data with 120 classes and even setups for training and odd setups for testing.
> 2. I make the changes in the yaml config file and following the same procedure as given for the NTU RGB 60.
> 
> I am getting decent accuracy for the **Cross-Subject protocol** but really low on **Cross setup**.
> What can be the reason for this?

May I ask how long does you spend on training your model ?

**Comment by czhaneva** [comment]
May I ask how long did it take to train the model ?

**Comment by Anirudh257** [comment]
@Roy790422795 It takes almost 2 days to train the model on a single GPU on my university cluster. The batch-size is too large.

**Comment by dangao250** [comment]
Can I have the dataset, please

**Comment by Anirudh257** [comment]
@dangao250 You can go to the NTU 120 website and request for the link to download the dataset.

**Comment by dangao250** [comment]
> @dangao250 You can go to the NTU 120 website and request for the link to download the dataset.

I applied on the official website but haven't replied for a month

**Comment by Anirudh257** [comment]
@dangao250 I also faced the same issue. You should mail the authors listed on the paper. They mailed promptly and I was able to download the dataset.

**Comment by FesianXu** [comment]
@Anirudh257  Hi， Have you tried it on NTU 60? How about the performance of the model on the NTU RGBD 60 ?   I want a comparision on my own database. Thx

**Comment by Anirudh257** [comment]
@FesianXu I haven't trained on NTU-60 but I think that it should get done faster than NTU-120 in a day.  While comparing on your own dataset, ensure that the graph is properly constructed and the ordering is correct.

**Comment by FesianXu** [comment]
@Anirudh257 Thanks for your response. I will try.
