### ISSUE TITLE
RuntimeError: after reduction step 1: device-side assert triggered

### ISSUE THREAD

**Issue by ouss3ma** [limaosen0/AS-GCN#14]
i got this error when i run: python main.py recognition -c config/as_gcn/ntu-xsub/train.yaml

I'm using the default conf train.yaml (4 gpus)

[09.25.19|12:58:47] Training epoch: 10
/scratch/oussema/AS-GCN/processor/io.py:35: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  default_arg = yaml.load(f)
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [17,0,0] Assertion `t >= 0 && t < n_classes` failed.
/scratch/oussema/AS-GCN/net/utils/adj_learn.py:11: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  soft_max_1d = F.softmax(trans_input)
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    p.start()
  File "/scratch/oussema/AS-GCN/processor/processor.py", line 111, in start
    self.train(training_A=False)
  File "/scratch/oussema/AS-GCN/processor/recognition.py", line 163, in train
    loss_recon = self.loss_pred(pred, target)
  File "/home/oussema/as-gcn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oussema/as-gcn/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 431, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/oussema/as-gcn/lib/python3.6/site-packages/torch/nn/functional.py", line 2190, in mse_loss
    ret = torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
RuntimeError: after reduction step 1: device-side assert triggered

**Comment by Z2HENG** [comment]
Have you solved your problem? How did you solve it? Thanks

**Comment by Neptunelover** [comment]
Have you solved your problem? How did you solve it? Thanks
