### ISSUE TITLE
ModuleNotFoundError: No module named 'processor.demo'

### ISSUE THREAD

**Issue by Anirudh257** [limaosen0/AS-GCN#2]
First of all, thanks a lot for providing this code. It is a great help for beginners like me.

I am trying to train AS-GCN on NTU RGB-D 120 ( the new dataset). I convert the data into the format: **[N x C x max_frame_len x no_joints x no_subjects]**, N = total number of samples,
C = total number of channels[3], max_frame_len = 300, no_joints= 25, no_subjects = 2 and save it in a .npy format.

I am then setting up the config.yaml file and trying to train using:

> Train: python main.py recognition -c config/as_gcn/ntu-xsub/train.yaml

but I keep getting this **ModuleNotFoundError: No module named 'processor.demo'**.

In the Processor folder, I couldn't find any file with the name **demo** either. It will be great if you could provide it if it is necessary for the training of the program.

**Comment by jfgg95** [comment]
I have read the code of [st-gcn](https://github.com/yysijie/st-gcn) before, which is very similar to this. I think this line of code is not important. You can comment it out.

**Comment by Anirudh257** [comment]
Thanks @jfgg95

**Comment by czhaneva** [comment]
@jfgg95 Have you run the code of st-gcn? I have run it several times but can't get the results described in the paper. And I don't kown the reason. I will appreciate it if you could reply me.

**Comment by jfgg95** [comment]
@Roy790422795  I ran the  [st-gcn](https://github.com/yysijie/st-gcn) code last year and the results are very close to the results in the paper, which are 87%, 83%.
The software environment is python=3.6 pytorch=0.4.1, using a GPU(NVIDIA GeForce 1080ti)，60epoch

**Comment by czhaneva** [comment]
> @Roy790422795  I ran the  st-gcn code last year and the results are very close to the results in the paper, which are 87%, 83%.
> The software environment is python=3.6 pytorch=0.4.1, using a GPU(NVIDIA GeForce 1080ti)，60epoch

Thank you for your reply. eeee. Have you preprocessed the data? Or you just use the orignal data generated from the ntu_gendata.py, or use the data download from baidu cloud.

**Comment by jfgg95** [comment]
@Roy790422795 I have not done any processing on the data. I only used the skeleton data in the nturgbd_skeletons.zip and refactored it with ntu_gendata.py.

**Comment by czhaneva** [comment]
> @Roy790422795 I have not done any processing on the data. I only used the skeleton data in the nturgbd_skeletons.zip and refactored it with ntu_gendata.py.

Thank you very much! Maybe I should git clone the code again to check whether I changed something unguarded

**Comment by dangao250** [comment]
> @Roy790422795 I have not done any processing on the data. I only used the skeleton data in the nturgbd_skeletons.zip and refactored it with ntu_gendata.py.

![image](https://user-images.githubusercontent.com/44044170/68913594-bf0cd700-0796-11ea-951e-19aa2b39fedf.png)

**Comment by dangao250** [comment]
> @Roy790422795 I ran the [st-gcn](https://github.com/yysijie/st-gcn) code last year and the results are very close to the results in the paper, which are 87%, 83%.
> The software environment is python=3.6 pytorch=0.4.1, using a GPU(NVIDIA GeForce 1080ti)，60epoch
![image](https://user-images.githubusercontent.com/44044170/68914120-8a9a1a80-0798-11ea-9186-588fd584b981.png)

**Comment by dangao250** [comment]
> @Roy790422795 I have not done any processing on the data. I only used the skeleton data in the nturgbd_skeletons.zip and refactored it with ntu_gendata.py.

![image](https://user-images.githubusercontent.com/44044170/68914685-54f63100-079a-11ea-9d09-529f4db561ee.png)
How to solve this error?

**Comment by dangao250** [comment]
> @Roy790422795 I have not done any processing on the data. I only used the skeleton data in the nturgbd_skeletons.zip and refactored it with ntu_gendata.py.



> @Roy790422795 I have not done any processing on the data. I only used the skeleton data in the nturgbd_skeletons.zip and refactored it with ntu_gendata.py.



> I have read the code of [st-gcn](https://github.com/yysijie/st-gcn) before, which is very similar to this. I think this line of code is not important. You can comment it out.
![image](https://user-images.githubusercontent.com/44044170/68914731-76efb380-079a-11ea-9610-1b1f7f2d89ab.png)

How to solve this error?

**Comment by dangao250** [comment]
> Thanks @jfgg95

![image](https://user-images.githubusercontent.com/44044170/68914991-5b38dd00-079b-11ea-928b-2a6cc01f8bd5.png)
Have you solved it?

**Comment by dangao250** [comment]
> Thanks @jfgg95

processor.demo   Have you reproduced this forecast code?
