### ISSUE TITLE
Can I directly use the dataset of st-gcn？

### ISSUE THREAD

**Issue by yypnogg1011** [limaosen0/AS-GCN#47]
I have completed the related work of ST-GCN, and I found that your data processing code is similar to their code, so can I use the ST-GCN dataset  on your code directly?

-----
ok,I already understand

**Comment by Fanthers** [comment]
> I have completed the related work of ST-GCN, and I found that your data processing code is similar to their code, so can I use the ST-GCN dataset on your code directly?
> 
> ok,I already understand

Can you tell me how you do it?
