### ISSUE TITLE
The accuracy is low.

### ISSUE THREAD

**Issue by Infinite-Song** [limaosen0/AS-GCN#6]
I'm really interested in the paper! I have trained this model about 100 epochs for several times. Howerver, I can't achieve the results described by the paper in NTU RGBD dataset. 

1. I have tried to train the model by using the hyper-parameters given by the yaml file, the accuracy is only about 48%.
![image](https://user-images.githubusercontent.com/26101174/61612496-5e123e00-ac91-11e9-9a80-a937aebc358b.png)

2. I noticed the hyper-parameters is different from the paper, so I changed them to  be the same as the paper.  Finally, the accuracy is about 80%.

3. I have also tried the older branch code committed by the author in May. The link is here:   https://github.com/limaosen0/AS-GCN/tree/8efd973a8ecd37e22bb976de5cb49e1f7cb5724e
But the accuracy is about 74%. I used the hyper-parameters given by the paper. The loss is about 0.38 after about 100 epochs， and it seems the loss will no longer decrease.
![image](https://user-images.githubusercontent.com/26101174/61613593-52744680-ac94-11e9-96a4-8c2d3a52fd49.png)

Does anyone achieve the results discribed by the paper? Can anyone tell me what's wrong with my experiments? Hope your reply! Thanks!

**Comment by LJ0109** [comment]
Hi,When I run the main function, I encountered this problem, how can I solve it? Thank you.

Traceback (most recent call last):
File "D:/AS-GCN-master/main.py", line 22, in
Processor = processors[arg.processor]
KeyError: None

**Comment by dangao250** [comment]
> I'm really interested in the paper! I have trained this model about 100 epochs for several times. Howerver, I can't achieve the results described by the paper in NTU RGBD dataset.
> 
> 1. I have tried to train the model by using the hyper-parameters given by the yaml file, the accuracy is only about 48%.
>    ![image](https://user-images.githubusercontent.com/26101174/61612496-5e123e00-ac91-11e9-9a80-a937aebc358b.png)
> 2. I noticed the hyper-parameters is different from the paper, so I changed them to  be the same as the paper.  Finally, the accuracy is about 80%.
> 3. I have also tried the older branch code committed by the author in May. The link is here:   https://github.com/limaosen0/AS-GCN/tree/8efd973a8ecd37e22bb976de5cb49e1f7cb5724e
>    But the accuracy is about 74%. I used the hyper-parameters given by the paper. The loss is about 0.38 after about 100 epochs， and it seems the loss will no longer decrease.
>    ![image](https://user-images.githubusercontent.com/26101174/61613593-52744680-ac94-11e9-96a4-8c2d3a52fd49.png)
> 
> Does anyone achieve the results discribed by the paper? Can anyone tell me what's wrong with my experiments? Hope your reply! Thanks!

请问你可以把你数据集分享一下可以吗  我希望你可以加我qq 我对这个方向很感兴趣

**Comment by dangao250** [comment]
> I'm really interested in the paper! I have trained this model about 100 epochs for several times. Howerver, I can't achieve the results described by the paper in NTU RGBD dataset.
> 
> 1. I have tried to train the model by using the hyper-parameters given by the yaml file, the accuracy is only about 48%.
>    ![image](https://user-images.githubusercontent.com/26101174/61612496-5e123e00-ac91-11e9-9a80-a937aebc358b.png)
> 2. I noticed the hyper-parameters is different from the paper, so I changed them to  be the same as the paper.  Finally, the accuracy is about 80%.
> 3. I have also tried the older branch code committed by the author in May. The link is here:   https://github.com/limaosen0/AS-GCN/tree/8efd973a8ecd37e22bb976de5cb49e1f7cb5724e
>    But the accuracy is about 74%. I used the hyper-parameters given by the paper. The loss is about 0.38 after about 100 epochs， and it seems the loss will no longer decrease.
>    ![image](https://user-images.githubusercontent.com/26101174/61613593-52744680-ac94-11e9-96a4-8c2d3a52fd49.png)
> 
> Does anyone achieve the results discribed by the paper? Can anyone tell me what's wrong with my experiments? Hope your reply! Thanks!

How to solve this error?
![image](https://user-images.githubusercontent.com/44044170/68914618-16607680-079a-11ea-8c6f-57ddce7349b9.png)

**Comment by Infinite-Song** [comment]
> > I'm really interested in the paper! I have trained this model about 100 epochs for several times. Howerver, I can't achieve the results described by the paper in NTU RGBD dataset.
> > 
> > 1. I have tried to train the model by using the hyper-parameters given by the yaml file, the accuracy is only about 48%.
> >    ![image](https://user-images.githubusercontent.com/26101174/61612496-5e123e00-ac91-11e9-9a80-a937aebc358b.png)
> > 2. I noticed the hyper-parameters is different from the paper, so I changed them to  be the same as the paper.  Finally, the accuracy is about 80%.
> > 3. I have also tried the older branch code committed by the author in May. The link is here:   https://github.com/limaosen0/AS-GCN/tree/8efd973a8ecd37e22bb976de5cb49e1f7cb5724e
> >    But the accuracy is about 74%. I used the hyper-parameters given by the paper. The loss is about 0.38 after about 100 epochs， and it seems the loss will no longer decrease.
> >    ![image](https://user-images.githubusercontent.com/26101174/61613593-52744680-ac94-11e9-96a4-8c2d3a52fd49.png)
> > 
> > Does anyone achieve the results discribed by the paper? Can anyone tell me what's wrong with my experiments? Hope your reply! Thanks!
> 
> How to solve this error?
> ![image](https://user-images.githubusercontent.com/44044170/68914618-16607680-079a-11ea-8c6f-57ddce7349b9.png)

Comment the relevant lines directly. Here is the solution: https://github.com/limaosen0/AS-GCN/issues/2

**Comment by github2016-yuan** [comment]
@Infinite-Song Hello, Do you get nan err while trainning?
