### ISSUE TITLE
Data sets help

### ISSUE THREAD

**Issue by LJ0109** [limaosen0/AS-GCN#8]
Hello, I am very interested in your thesis, but it is difficult to download the dataset. If you can see this message, can you pass it to me？ thank you.

**Comment by BigLazyPig** [comment]
NTU-RGBD data set needs official authorization to download, so you have to register to download it yourself, and no one else can send it to you. 

NTU这个数据集需要官方授权才能下载，所以你得去注册申请，自己下载，其他人不能传给你。如果你在国内的话，获得链接以后可以直接使用迅雷下载，只需要里面的skeleton数据，大概6G，下载还是很快的。希望对你有用。

**Comment by LJ0109** [comment]
Ok, thank you, I originally registered with QQ mailbox, but I did not pass the review. The email reply needs further verification. I sent the email again and I have not received a reply yet.
好的，谢谢你，我最初使用QQ邮箱注册，但是没有审核通过，邮件回复需要进一步验证，我又再一次发送了邮件，目前还没有收到回复。





------------------ 原始邮件 ------------------
发件人: "Wensong Chan"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 上午9:53
收件人: "limaosen0/AS-GCN"<AS-GCN@noreply.github.com>;
抄送: "SILENCE"<1543565400@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [limaosen0/AS-GCN] Data sets help (#8)




NTU-RGBD data set needs official authorization to download, so you have to register to download it yourself, and no one else can send it to you.
 
NTU这个数据集需要官方授权才能下载，所以你得去注册申请，自己下载，其他人不能传给你。如果你在国内的话，获得链接以后可以直接使用迅雷下载，只需要里面的skeleton数据，大概6G，下载还是很快的。希望对你有用。

**Comment by LJ0109** [comment]
Ok, thank you, I originally registered with QQ mailbox, but I did not pass the review. The email reply needs further verification. I sent the email again and I have not received a reply yet.
好的，谢谢你，我最初使用QQ邮箱注册，但是没有审核通过，邮件回复需要进一步验证，我又再一次发送了邮件，目前还没有收到回复。

**Comment by BigLazyPig** [comment]
没事~我之前也是这样的，进一步验证可能需要等一段时间。

**Comment by dangao250** [comment]
May I have a data set? My QQ is 1337932153
请问可不可以传我一份数据集 我qq是1337932153
